# Generated by Django 3.2.20 on 2023-10-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
