# Generated by Django 3.2.20 on 2023-10-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231005_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_packaging_color', models.CharField(choices=[('pink', 'Pink Box'), ('gold', 'Gold Box')], default='pink', max_length=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
