# Generated by Django 3.2.20 on 2023-09-29 13:20

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_membership_status'),
        ('profiles', '0003_alter_userprofile_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_status',
            field=models.ForeignKey(default=profiles.models.get_non_member_status, on_delete=django.db.models.deletion.PROTECT, related_name='user_membership', to='membership.membership'),
        ),
    ]
