# Generated by Django 3.2.20 on 2023-10-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_vipbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipbox',
            options={'verbose_name_plural': 'VIP boxes'},
        ),
    ]
