# Generated by Django 3.2.20 on 2023-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('Member', 'Member'), ('Non-Member', 'Non-Member'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
