# Generated by Django 3.2.20 on 2023-10-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membership_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='choose_vip_box',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='vip_box',
        ),
        migrations.DeleteModel(
            name='VIPBox',
        ),
    ]
