# Generated by Django 3.2.20 on 2023-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
