# Generated by Django 3.2.20 on 2023-09-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='star_ingredients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herbs.herb'),
        ),
        migrations.AddField(
            model_name='skintype',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
