# Generated by Django 3.2.20 on 2023-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230907_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='milliliter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
