# Generated by Django 3.2.20 on 2023-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231006_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='member_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='member_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
    ]
