# Generated by Django 3.2.20 on 2023-09-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_milliliter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trial_size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
