# Generated by Django 3.2.20 on 2023-10-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231006_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='member_price',
        ),
    ]
