# Generated by Django 3.2.20 on 2023-09-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0001_initial'),
        ('products', '0005_rename_trial_size_product_name_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_print',
        ),
        migrations.AlterField(
            model_name='product',
            name='star_ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='herbs.herb'),
        ),
    ]
